output "cluster_id" {
  description = "ROSA Cluster ID"
  value       = rhcs_cluster_rosa_classic.this.id
}

output "cluster_api_url" {
  description = "Cluster API URL (internal — requires VPN/Direct Connect)"
  value       = "https://api.${var.cluster_name}.${var.base_domain}:6443"
}

output "cluster_console_url" {
  description = "OpenShift Console URL (internal — requires VPN/Direct Connect)"
  value       = "https://console-openshift-console.apps.${var.cluster_name}.${var.base_domain}"
}

output "admin_username" {
  description = "Cluster admin username"
  value       = rhcs_cluster_rosa_classic.this.admin_credentials.username
}

output "admin_password" {
  description = "Cluster admin password (auto-generated by RHCS)"
  value       = rhcs_cluster_rosa_classic.this.admin_credentials.password
  sensitive   = true
}
